
POST http://localhost:5000/schema_setting
content-type: application/json

{
    "schema_name":"test_2",
    "columns":[
        {
            "column_name": "age",
            "type": "Number",
            "ref":""
        },
        {
            "column_name": "addr",
            "type": "String",
            "ref":""
        },
        {
            "column_name": "post-code",
            "type": "String",
            "ref":""
        }
    ]
}
